# Generated by Django 5.0.3 on 2024-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
    ]
