# Generated by Django 5.0.3 on 2024-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landfill_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='model_version',
            field=models.CharField(default='v1', max_length=100),
        ),
    ]
